### ISSUE TITLE
Garage Door function

### ISSUE THREAD

**Issue by AudiQ6-Richterswil** [electrichasgoneaudi/q6-e-tron#28] opened 2024-09-28 12:05 UTC
Wtf...Who would have thought Audi would go to all the effort to add all the development and electro-mechanical equipment as a standard feature for both electric charging flaps (even though my VW Golf GTE manual open charging flap works great)... but then decide that they would bury the garage door opening feature as an OPTION by putting it into the MMI PRO Plus package which costs an additional 650 CHF in Switzerland (I dont care about the car theft features)...how can this feature not be standard??? and now I didnt order that option not realizing the button I would use at least twice a day is not in my car, but I have standard the BS electric charging flap opener (I have used it once on the right side) as standard...

**Comment by R3ffoTz** [comment] 2024-09-28 12:30
Not a bug?

**Comment by bwa** [comment] 2024-09-28 12:32
Yes, this will be closed as not a bug

**Closed by bwa** 2024-09-28 12:32 UTC
